---
apiVersion: apps/v1
kind: Deployment

metadata:
        name: ngnix-deploy


        labels:
                app: ngnix
spec:
        replicas: 2
        selector:
                matchLabels:
                        app: ngnix
        template:
                metadata:
                        name: ngnix-pod
                        labels:
                                app: ngnix
                spec:
                    containers:
                     -  name: ngnix-container
                        image: docker89781/image:latest
                        imagePullPolicy: Always
                        ports:
                            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
        name: my-service

        labels:
                app: ngnix
spec:
        selector:
                app: ngnix
        type: LoadBalancer

        ports:
                - nodePort: 31001
                  port: 8080
                  targetPort: 8080
